import XCTest

final class ProjectConfigurationTests: XCTestCase {
    func testIPadBuildDeclaresFullScreenAndAllOrientations() throws {
        let testFileURL = URL(fileURLWithPath: #filePath)
        let projectRoot = testFileURL
            .deletingLastPathComponent()
            .deletingLastPathComponent()
        let projectFile = projectRoot.appendingPathComponent("project.yml")
        let projectText = try String(contentsOf: projectFile)

        XCTAssertTrue(projectText.contains("UIRequiresFullScreen: true"))
        XCTAssertTrue(projectText.contains("UISupportedInterfaceOrientations~ipad:"))
        XCTAssertTrue(projectText.contains("UIInterfaceOrientationPortrait"))
        XCTAssertTrue(projectText.contains("UIInterfaceOrientationPortraitUpsideDown"))
        XCTAssertTrue(projectText.contains("UIInterfaceOrientationLandscapeLeft"))
        XCTAssertTrue(projectText.contains("UIInterfaceOrientationLandscapeRight"))
    }

    func testLaunchHandwritingIsBundledAndNotUserConfigurable() throws {
        let testFileURL = URL(fileURLWithPath: #filePath)
        let projectRoot = testFileURL
            .deletingLastPathComponent()
            .deletingLastPathComponent()
        let appRootText = try String(contentsOf: projectRoot.appendingPathComponent("SmartChart/App/AppRootView.swift"))
        let libraryText = try String(contentsOf: projectRoot.appendingPathComponent("SmartChart/Features/Library/LibraryView.swift"))
        let bundledLaunchSampleURL = projectRoot
            .appendingPathComponent("SmartChart/Resources/Launch/IChartCanonicalLaunchHandwriting.json")
        let bundledLaunchSampleText = try String(contentsOf: bundledLaunchSampleURL)

        XCTAssertTrue(appRootText.contains("IChartLaunchScreenView"))
        XCTAssertTrue(appRootText.contains("bundledCanonicalLaunchSample"))
        XCTAssertTrue(appRootText.contains("IChartCanonicalLaunchHandwriting"))
        XCTAssertTrue(appRootText.contains("subdirectory: canonicalResourceSubdirectory"))
        XCTAssertTrue(appRootText.contains("bundle.url("))
        XCTAssertFalse(appRootText.contains("@AppStorage"))
        XCTAssertFalse(appRootText.contains("iChartLaunchHandwriting"))
        XCTAssertFalse(libraryText.contains("Launch Handwriting"))
        XCTAssertTrue(bundledLaunchSampleText.contains("\"strokes\""))
    }

    func testChordConfirmationOffersKeyboardManualEntry() throws {
        let projectRoot = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
        let sheetText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("SmartChart/Features/Editor/Components/ChordInkSheetViews.swift")
        )

        XCTAssertTrue(sheetText.contains("No confident suggestions"))
        XCTAssertTrue(sheetText.contains("Open keyboard for manual chord entry"))
        XCTAssertTrue(sheetText.contains("systemImage: \"keyboard\""))
    }

    func testSettingsContainUserInfoWithoutPaymentInfo() throws {
        let projectRoot = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
        let libraryText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("SmartChart/Features/Library/LibraryView.swift")
        )

        XCTAssertTrue(libraryText.contains("User Info"))
        XCTAssertTrue(libraryText.contains("@State private var userEmail"))
        XCTAssertTrue(libraryText.contains("@State private var userPhone"))
        XCTAssertTrue(libraryText.contains("@State private var userAddress"))
        XCTAssertFalse(libraryText.contains("iChartUserEmail"))
        XCTAssertFalse(libraryText.contains("iChartUserPhone"))
        XCTAssertFalse(libraryText.contains("iChartUserAddress"))
        XCTAssertFalse(libraryText.contains("iChartUserPaymentSummary"))
        XCTAssertFalse(libraryText.contains("Payment Info"))
        XCTAssertTrue(libraryText.contains("Resend Email"))
        XCTAssertTrue(libraryText.contains("Open the verification link"))
    }

    func testManualTextEntryPopoutsExposeKeyboardButtons() throws {
        let projectRoot = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
        let libraryText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("SmartChart/Features/Library/LibraryView.swift")
        )
        let headerSheetText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("SmartChart/Features/Editor/Components/ChartHeaderSheetView.swift")
        )
        let editorText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("SmartChart/Features/Editor/EditorView.swift")
        )
        let chordSheetText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("SmartChart/Features/Editor/Components/ChordInkSheetViews.swift")
        )

        XCTAssertTrue(libraryText.contains("IChartKeyboardFocusButton"))
        XCTAssertTrue(libraryText.contains("field: .firstName"))
        XCTAssertTrue(libraryText.contains("accessibilityLabel: \"Open keyboard for \\(title)\""))
        XCTAssertTrue(libraryText.contains("Open keyboard for chart title"))
        XCTAssertTrue(libraryText.contains("Open keyboard for project title"))
        XCTAssertTrue(libraryText.contains("Open keyboard for variant title"))
        XCTAssertTrue(headerSheetText.contains("focusedField = .title"))
        XCTAssertTrue(headerSheetText.contains("Open keyboard for \\(title)"))
        XCTAssertTrue(editorText.contains("Open keyboard for text entry"))
        XCTAssertTrue(chordSheetText.contains("Open keyboard for chord correction"))
    }

    func testFirstRunAccountLandingIsMandatoryAndCollectsName() throws {
        let projectRoot = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
        let libraryText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("SmartChart/Features/Library/LibraryView.swift")
        )
        let appRootText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("SmartChart/App/AppRootView.swift")
        )
        let authStoreText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("SmartChart/App/Auth/IChartAuthStore.swift")
        )
        let profileNamesMigrationText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("supabase/migrations/20260614183703_add_profile_names.sql")
        )
        let lockedProfileNamesMigrationText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("supabase/migrations/20260614183718_lock_profile_account_names.sql")
        )
        let rlsTestText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("supabase/tests/rls_smoke.sql")
        )
        let planPolicyText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("docs/ichart-plan-policy-source-of-truth.md")
        )

        XCTAssertTrue(libraryText.contains("IChartFirstRunAccountLandingView"))
        XCTAssertTrue(libraryText.contains("var requiresNameForSignup = true"))
        XCTAssertTrue(libraryText.contains("requiresNameForSignup: true"))
        XCTAssertTrue(libraryText.contains("First Name"))
        XCTAssertTrue(libraryText.contains("Last Name"))
        XCTAssertTrue(libraryText.contains("Account Name"))
        XCTAssertTrue(libraryText.contains("IChartSettingsLockedValueRow"))
        XCTAssertTrue(libraryText.contains("Set at account creation"))
        XCTAssertTrue(libraryText.contains(".fullScreenCover(isPresented: $showingAccountLanding)"))
        XCTAssertTrue(libraryText.contains(".frame(maxWidth: 640)"))
        XCTAssertTrue(libraryText.contains(".frame(minHeight: proxy.size.height, alignment: .center)"))
        XCTAssertTrue(libraryText.contains(".interactiveDismissDisabled(true)"))
        XCTAssertTrue(libraryText.contains("showsSignedInActions: false"))
        XCTAssertTrue(libraryText.contains("authStore.state.isVerifiedSignedIn"))
        XCTAssertTrue(libraryText.contains("Label(\"Continue\", systemImage: \"arrow.right\")"))
        XCTAssertTrue(libraryText.contains("IChartLaunchScreenView("))
        XCTAssertTrue(libraryText.contains("IChartLaunchHandwritingSample.bundledCanonicalLaunchSample()"))
        XCTAssertTrue(libraryText.contains("completeFirstRunAccountLanding"))
        XCTAssertTrue(libraryText.contains("hasSeenAccountLanding = true"))
        XCTAssertFalse(libraryText.contains("Continue to Charts"))
        XCTAssertFalse(libraryText.contains("Button(\"Close\")"))
        XCTAssertTrue(appRootText.contains("hasSeenAccountLandingKey"))
        XCTAssertTrue(appRootText.contains("UserDefaults.standard.bool(forKey: Self.hasSeenAccountLandingKey)"))
        XCTAssertTrue(appRootText.contains("struct IChartLaunchScreenView"))
        XCTAssertTrue(authStoreText.contains("firstName = \"first_name\""))
        XCTAssertTrue(authStoreText.contains("lastName = \"last_name\""))
        XCTAssertTrue(authStoreText.contains("data: signupMetadata(firstName: firstName, lastName: lastName)"))
        XCTAssertFalse(authStoreText.contains("firstName = profile.firstName"))
        XCTAssertFalse(authStoreText.contains("lastName = profile.lastName"))
        XCTAssertTrue(profileNamesMigrationText.contains("add column if not exists first_name text"))
        XCTAssertTrue(profileNamesMigrationText.contains("add column if not exists last_name text"))
        XCTAssertTrue(profileNamesMigrationText.contains("new.raw_user_meta_data ->> 'first_name'"))
        XCTAssertTrue(profileNamesMigrationText.contains("new.raw_user_meta_data ->> 'last_name'"))
        XCTAssertTrue(lockedProfileNamesMigrationText.contains("revoke update (first_name, last_name)"))
        XCTAssertTrue(lockedProfileNamesMigrationText.contains("private.lock_profile_account_names"))
        XCTAssertTrue(rlsTestText.contains("client cannot update locked profile name fields"))
        XCTAssertTrue(planPolicyText.contains("In-app account creation requires first name, last name, email, and password"))
        XCTAssertTrue(planPolicyText.contains("First and last name are locked account identity fields after signup"))
    }

    func testHomeShellPrimaryControlsKeepExplicitHitAreas() throws {
        let projectRoot = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
        let libraryText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("SmartChart/Features/Library/LibraryView.swift")
        )

        XCTAssertTrue(libraryText.contains(".frame(minWidth: 180, minHeight: 44)"))
        XCTAssertTrue(libraryText.contains(".contentShape(RoundedRectangle(cornerRadius: 8, style: .continuous))"))
        XCTAssertTrue(libraryText.contains("IChartHomeSidebarButton"))
        XCTAssertTrue(libraryText.contains("IChartNewChartControl"))
    }

    func testHelpSurfaceIncludesTutorialWalkthrough() throws {
        let projectRoot = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
        let libraryText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("SmartChart/Features/Library/LibraryView.swift")
        )
        let editorText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("SmartChart/Features/Editor/EditorView.swift")
        )
        let canvasHostText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("SmartChart/Features/Editor/Components/LeadSheetCanvasHostView.swift")
        )
        let setupSheetText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("SmartChart/Features/Editor/Components/ChartSetupSheetView.swift")
        )
        let editorMenuTabLabelText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("SmartChart/Features/Editor/Components/EditorMenuTabLabel.swift")
        )
        let headerSheetText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("SmartChart/Features/Editor/Components/ChartHeaderSheetView.swift")
        )
        let typographySheetText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("SmartChart/Features/Editor/Components/ChartTypographySheetView.swift")
        )
        let notationRendererText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("SmartChart/Features/Editor/Components/LeadSheetNotationRenderer.swift")
        )
        let appearanceSheetText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("SmartChart/Features/Editor/Components/ChartAppearanceSheetView.swift")
        )
        let chartModelText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("SmartChart/Models/Chart.swift")
        )
        let measureTimingText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("SmartChart/Services/MeasureTimingValidator.swift")
        )
        let chordInkSheetText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("SmartChart/Features/Editor/Components/ChordInkSheetViews.swift")
        )

        XCTAssertTrue(libraryText.contains("case tutorial"))
        XCTAssertTrue(libraryText.contains("selectedHelpTopic ?? .tutorial"))
        XCTAssertTrue(libraryText.contains("IChartTutorialGuide"))
        XCTAssertTrue(libraryText.contains("IChartHelpArticlePage"))
        XCTAssertTrue(libraryText.contains("IChartHelpArticleSection"))
        XCTAssertTrue(libraryText.contains("expandedSectionIDs"))
        XCTAssertTrue(libraryText.contains("toggleSection"))
        XCTAssertTrue(libraryText.contains("chevron.down"))
        XCTAssertTrue(libraryText.contains("chevron.right"))
        XCTAssertTrue(libraryText.contains("Collapse section"))
        XCTAssertTrue(libraryText.contains("Expand section"))
        XCTAssertTrue(libraryText.contains("isExpanded: expandedSectionIDs.contains(section.id)"))
        XCTAssertTrue(libraryText.contains("Start Hands-On Tour"))
        XCTAssertTrue(libraryText.contains("Read through the main iChart systems here"))
        XCTAssertTrue(libraryText.contains("Welcome To iChart"))
        XCTAssertTrue(libraryText.contains("Write the chart. Share with the band."))
        XCTAssertTrue(libraryText.contains("Getting Started"))
        XCTAssertTrue(libraryText.contains("Charts, Projects, And PDFs"))
        XCTAssertTrue(libraryText.contains("Editor Navigation"))
        XCTAssertTrue(libraryText.contains("Use Page for whole-chart setup"))
        XCTAssertTrue(libraryText.contains("Use Measures only for measure layout"))
        XCTAssertTrue(libraryText.contains("Use Repeats only for repeat barlines"))
        XCTAssertTrue(libraryText.contains("Use Coda for point roadmap markers"))
        XCTAssertTrue(libraryText.contains("Use Text only for cue text"))
        XCTAssertTrue(libraryText.contains("Use Time only for measure-level time-signature changes"))
        XCTAssertTrue(libraryText.contains("Use Rhythm for supported rhythm notation ink"))
        XCTAssertTrue(libraryText.contains("Use Chord only for handwritten chord entry"))
        XCTAssertTrue(libraryText.contains("Use Free-Hand only for marks that should remain as handwritten ink"))
        XCTAssertTrue(libraryText.contains("Account, Pro, And Forums"))
        XCTAssertTrue(libraryText.contains("Settings"))
        XCTAssertTrue(libraryText.contains("Instrument Transposition chooses the instrument preset"))
        XCTAssertTrue(libraryText.contains("common /4 and /8 meters"))
        XCTAssertTrue(libraryText.contains("3/8, 5/8, 6/8, 7/8, 9/8, and 12/8"))
        XCTAssertTrue(libraryText.contains("The top row contains Page, Select, Measures, Repeats, Coda, Text, Time, Rhythm when available, Chord, and Free-Hand."))
        XCTAssertTrue(libraryText.contains("Delete removes the selected measure. Range starts a delete range, Delete To finishes it, and Clear cancels the pending range."))
        XCTAssertFalse(libraryText.contains("Del Thru finishes it"))
        XCTAssertTrue(libraryText.contains("Start marks the first measure of a repeat span. End Rep closes the span at the selected measure."))
        XCTAssertTrue(libraryText.contains("New Row starts the selected measure on a new row"))
        XCTAssertTrue(libraryText.contains("Remove Repeat removes repeat markings"))
        XCTAssertFalse(libraryText.contains("New Sys starts"))
        XCTAssertFalse(libraryText.contains("Rm Rep removes"))
        XCTAssertTrue(libraryText.contains("Add Coda, To Coda, Segno, D.S., D.S. al Coda, D.C., D.C. al Fine, Fine, or N.C."))
        XCTAssertFalse(libraryText.contains("Add 𝄌, To 𝄌, 𝄋, D.S., D.S. al 𝄌"))
        XCTAssertTrue(libraryText.contains("Select a Coda marker, drag it left or right within its measure, or tap its x to delete it."))
        XCTAssertFalse(libraryText.contains("Remove Roadmap Marker deletes the marker at the selected measure"))
        XCTAssertFalse(libraryText.contains("How do I start a chart?"))
        XCTAssertFalse(libraryText.contains("Can I export on Basic?"))
        XCTAssertTrue(libraryText.contains("Answers about Forums and why iChart uses accounts."))
        XCTAssertFalse(libraryText.contains("Answers for chart setup, handwriting tools, export, saved " + "charts, accounts, Pro, and Forums."))
        XCTAssertTrue(libraryText.contains("Forums are a Pro community chart library built around fixed PDF snapshots"))
        XCTAssertTrue(libraryText.contains("Why does iChart need an account?"))
        XCTAssertTrue(libraryText.contains("Account Identity"))
        XCTAssertFalse(libraryText.contains("Handwriting Corrections"))
        XCTAssertFalse(libraryText.contains("Fonts And Third-Party Notices"))
        XCTAssertFalse(libraryText.contains("should use"))
        XCTAssertTrue(libraryText.contains("Legal Policy"))
        XCTAssertTrue(libraryText.contains("Terms Of Use"))
        XCTAssertTrue(libraryText.contains("Subscriptions"))
        XCTAssertTrue(libraryText.contains("Only publish forum charts you have the right to share"))
        XCTAssertTrue(libraryText.contains("IChartGuidedTourStep"))
        XCTAssertTrue(libraryText.contains("iChartHasSeenGuidedTourOffer"))
        XCTAssertTrue(libraryText.contains("iChartPendingSimpleChartTour"))
        XCTAssertFalse(libraryText.contains("selected" + "SectionID"))
        XCTAssertFalse(libraryText.contains("starting " + "ke" + "y"))
        XCTAssertFalse(libraryText.contains("cle" + "f, and starting measure count"))
        XCTAssertFalse(libraryText.contains("K" + "ey, Time, And Cle" + "f"))
        XCTAssertFalse(setupSheetText.contains("Text(\"K" + "ey\")"))
        XCTAssertFalse(setupSheetText.contains("Picker(\"Cle" + "f\""))
        XCTAssertFalse(libraryText.contains("rushing the player"))
        XCTAssertFalse(libraryText.contains("Repeat controls stay out"))
        XCTAssertFalse(libraryText.contains("so chart structure stays consistent"))
        XCTAssertFalse(libraryText.contains("Use the Repeat row for repeat barlines, endings, DC"))
        XCTAssertFalse(libraryText.contains("Page And Header"))
        XCTAssertFalse(libraryText.contains("Time And Structure"))
        XCTAssertFalse(libraryText.contains("Instrument View"))
        XCTAssertFalse(libraryText.contains("instrument view"))
        XCTAssertFalse(libraryText.contains("Page setup for the chart time signature"))
        XCTAssertFalse(libraryText.contains("Chord Tool"))
        XCTAssertFalse(libraryText.contains("Link Roadmap Marker"))
        XCTAssertFalse(libraryText.contains("Clear Roadmap Link"))
        XCTAssertFalse(libraryText.contains("Use Help for this written guide"))
        XCTAssertFalse(libraryText.contains("Coda And Roadmap"))
        XCTAssertFalse(libraryText.contains("Rhythm Edit to select"))
        XCTAssertTrue(libraryText.contains("guidedTourStep = .welcome"))
        XCTAssertTrue(libraryText.contains("guidedTourStep = .newChart"))
        XCTAssertTrue(libraryText.contains("guidedTourStep = .simpleChart"))
        XCTAssertFalse(libraryText.contains("guidedTourStep = .charts"))
        XCTAssertTrue(libraryText.contains("startsGuidedSimpleChartTour ? .chordEntry : .browse"))
        XCTAssertTrue(editorText.contains("IChartEditorGuidedTourStep"))
        XCTAssertTrue(editorText.contains("IChartEditorGuidedTourPrompt"))
        XCTAssertTrue(editorText.contains("Tap Create Blank Page"))
        XCTAssertTrue(editorText.contains("Write a chord, then tap outside the lane"))
        XCTAssertTrue(editorText.contains("Tap a chord choice"))
        XCTAssertTrue(editorText.contains("Tap Done"))
        XCTAssertTrue(editorText.contains("Open Page for Setup, Export, Header, Instrument Transposition"))
        XCTAssertTrue(editorText.contains("Tap Page"))
        XCTAssertTrue(editorText.contains("advanceEditorGuidedTourAfterPageToolTapIfNeeded"))
        XCTAssertTrue(editorText.contains("Measures is only for measure layout"))
        XCTAssertTrue(editorText.contains("Use Add, Stack, First, Double, New Row or Join, Delete, Range, Delete To, and Clear"))
        XCTAssertFalse(editorText.contains("New Sys or Join"))
        XCTAssertFalse(editorText.contains("Del Thru"))
        XCTAssertTrue(editorText.contains("Remove Repeat, Remove Ending"))
        XCTAssertFalse(editorText.contains("Rm Rep"))
        XCTAssertFalse(editorText.contains("Rm End"))
        XCTAssertTrue(editorText.contains("Repeats is only for repeat structure"))
        XCTAssertTrue(editorText.contains("Coda is only for point roadmap markers: Coda, To Coda, Segno, D.S., D.S. al Coda"))
        XCTAssertTrue(editorText.contains("Select a marker, drag it left or right within the measure"))
        XCTAssertFalse(editorText.contains("Coda is only for point roadmap markers: 𝄌"))
        XCTAssertTrue(editorText.contains("Text(roadmapType.editorMenuDisplayText)"))
        XCTAssertFalse(editorText.contains("roadmapMarkerActiveToolActions"))
        XCTAssertFalse(editorText.contains("pendingRoadmapMarkerMoveID"))
        XCTAssertFalse(editorText.contains("Remove Roadmap Marker at Selected Measure"))
        XCTAssertFalse(editorText.contains("systemImage: roadmapType.editorMenuSystemImageName"))
        XCTAssertTrue(notationRendererText.contains("drawRoadmapLabel"))
        XCTAssertTrue(notationRendererText.contains("LeadSheetRoadmapLabelFitting"))
        XCTAssertTrue(notationRendererText.contains("fittedBaseFontSize"))
        XCTAssertTrue(notationRendererText.contains("NotationGlyphCatalog.coda"))
        XCTAssertTrue(notationRendererText.contains("NotationGlyphCatalog.segno"))
        XCTAssertFalse(notationRendererText.contains("markerPath.fill()"))
        XCTAssertFalse(notationRendererText.contains("markerPath.stroke()"))
        XCTAssertTrue(editorText.contains("systemImage: \"rectangle.split.3x1\""))
        XCTAssertTrue(editorText.contains("systemImage: \"music.note\""))
        XCTAssertTrue(typographySheetText.contains("To Coda"))
        XCTAssertFalse(typographySheetText.contains("To 𝄌"))
        XCTAssertTrue(editorText.contains("Meter(numerator: 7, denominator: 8)"))
        XCTAssertTrue(editorText.contains("ChordToolInputMode"))
        XCTAssertTrue(editorText.contains("Ink Only: handwritten chords stay as ink"))
        XCTAssertTrue(editorText.contains("recognizesChordInk: chordToolInputMode.recognizesChordInk"))
        XCTAssertTrue(editorText.contains("isSelected: chart.headerInputMode == .typed"))
        XCTAssertTrue(editorText.contains("isSelected: chart.headerInputMode == .handwritten"))
        XCTAssertTrue(headerSheetText.contains("private var headerModePicker"))
        XCTAssertTrue(headerSheetText.contains("draftHeaderInputMode == mode"))
        XCTAssertTrue(headerSheetText.contains("Color(red: 0.16, green: 0.38, blue: 0.82)"))
        XCTAssertTrue(editorText.contains("handleMeasureSelectedFromCanvas"))
        XCTAssertTrue(editorText.contains("handleChordSelectedFromCanvas"))
        XCTAssertTrue(editorText.contains("handleCueTextSelectedFromCanvas"))
        XCTAssertTrue(editorText.contains("handleRoadmapMarkerSelectedFromCanvas"))
        XCTAssertTrue(editorText.contains("selectedCueTextID == nil"))
        XCTAssertTrue(editorText.contains("selectedRoadmapMarkerID != nil"))
        XCTAssertTrue(canvasHostText.contains("roadmapMarkerHitTarget(at: location)"))
        XCTAssertTrue(canvasHostText.contains("cueTextHitTarget(at: location)"))
        XCTAssertTrue(canvasHostText.contains("selectedRoadmapMarkerID == nil"))
        XCTAssertTrue(canvasHostText.contains("drawRoadmapMarkerEditOverlay"))
        XCTAssertTrue(canvasHostText.contains("LeadSheetRoadmapMarkerEditOverlayGeometry"))
        XCTAssertTrue(canvasHostText.contains("deleteRoadmapMarker"))
        XCTAssertTrue(canvasHostText.contains("movePointRoadmapMarkerHorizontally"))
        XCTAssertTrue(canvasHostText.contains("panStartLocation(for: recognizer)"))
        XCTAssertTrue(canvasHostText.contains("lastRoadmapMarkerDragHitTarget"))
        XCTAssertFalse(canvasHostText.contains("drawRoadmapMarkerSelection"))
        XCTAssertTrue(canvasHostText.contains("drawCueTextSelection"))
        XCTAssertTrue(editorText.contains("Tap Measures"))
        XCTAssertTrue(editorText.contains("Tap Repeats"))
        XCTAssertTrue(editorText.contains("Tap Coda"))
        XCTAssertTrue(editorText.contains("Tap Free-Hand"))
        XCTAssertTrue(editorText.contains("contentPromptAlignment"))
        XCTAssertTrue(editorText.contains(".bottomTrailing"))
        XCTAssertTrue(editorText.contains("isGuidedChordConfirmation"))
        XCTAssertTrue(editorText.contains("!isGuidedChordConfirmation"))
        XCTAssertTrue(editorText.contains("editorGuidedTourStep = .chordDone"))
        XCTAssertTrue(editorText.contains("editorGuidedTourStep = .page"))
        XCTAssertTrue(editorText.contains("editorGuidedTourStep = .measuresActive"))
        XCTAssertTrue(editorText.contains("editorGuidedTourStep = .coda"))
        XCTAssertTrue(editorText.contains("editorGuidedTourStep = .freeHandActive"))
        XCTAssertTrue(editorText.contains("startPendingSimpleChartTourIfNeeded"))
        XCTAssertTrue(editorText.contains("advanceEditorGuidedTourIfNeeded"))
        XCTAssertTrue(editorText.contains("advanceEditorGuidedTourAfterSetupIfNeeded"))
        XCTAssertTrue(editorText.contains("advanceEditorGuidedTourAfterCodaToolTapIfNeeded"))
        XCTAssertFalse(editorText.contains("rushing the player"))
        XCTAssertFalse(editorText.contains("Page Tool"))
        XCTAssertFalse(editorText.contains("instrument view"))
        XCTAssertFalse(editorText.contains("Create single measures or stacks"))
        XCTAssertFalse(editorText.contains("Add repeat barlines and first or second endings"))
        XCTAssertFalse(editorText.contains("Keep these changes in Repeats instead of Measures"))
        XCTAssertFalse(editorText.contains("Add repeat barlines, endings, DC"))
        XCTAssertFalse(editorText.contains("Link Roadmap Marker at Selected Measure"))
        XCTAssertTrue(editorMenuTabLabelText.contains(".accessibilityLabel(\"Coda\")"))
        XCTAssertFalse(editorMenuTabLabelText.contains(".accessibilityLabel(\"Roadmap\")"))
        XCTAssertFalse(setupSheetText.contains("Jazz Chord Notation"))
        XCTAssertTrue(libraryText.contains("No Charts Yet"))
        XCTAssertTrue(libraryText.contains("Create a new chart to start writing."))
        XCTAssertFalse(libraryText.contains("Create a new chart to start the first project."))
        XCTAssertTrue(libraryText.contains("Not For Me"))
        XCTAssertFalse(libraryText.contains("Downvote"))
        XCTAssertTrue(appearanceSheetText.contains("Choose the notation symbol style used in the chart."))
        XCTAssertTrue(appearanceSheetText.contains("Section(\"Notation Font\")"))
        XCTAssertFalse(appearanceSheetText.contains("Choose the SMuFL notation family used for glyphs."))
        XCTAssertFalse(appearanceSheetText.contains("Section(\"SMuFL Font\")"))
        XCTAssertTrue(chartModelText.contains("Staff-based page for melody, chords, and standard notation."))
        XCTAssertFalse(chartModelText.contains("current Smart Chart workflow"))
        XCTAssertTrue(measureTimingText.contains("is tied to a rhythm position that changed"))
        XCTAssertTrue(measureTimingText.contains("This rhythm has"))
        XCTAssertFalse(measureTimingText.contains("rhythm slot that no longer exists after the beat map changed"))
        XCTAssertFalse(measureTimingText.contains("This beat map has"))
        XCTAssertTrue(editorText.contains("editable rhythm sketch"))
        XCTAssertFalse(editorText.contains("editable rhythm map"))
        XCTAssertTrue(editorText.contains("off the measure grid"))
        XCTAssertFalse(editorText.contains("misaligned with the beat grid"))
        XCTAssertTrue(editorText.contains("Add measures in this time signature?"))
        XCTAssertFalse(editorText.contains("Add measures of time?"))
        XCTAssertTrue(chordInkSheetText.contains("#if DEBUG && targetEnvironment(simulator)"))
        XCTAssertTrue(chordInkSheetText.contains("Ink sample capture"))
        XCTAssertTrue(chordInkSheetText.contains("Copy Ink Sample"))
        XCTAssertFalse(chordInkSheetText.contains("Fixture capture"))
        XCTAssertFalse(chordInkSheetText.contains("Copy Regression Fixture"))
        XCTAssertFalse(setupSheetText.contains("notationSection"))
    }

    func testChartConsolidationUsesSingleDeleteList() throws {
        let projectRoot = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
        let libraryText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("SmartChart/Features/Library/LibraryView.swift")
        )

        XCTAssertTrue(libraryText.contains("IChartChartConsolidationNotice"))
        XCTAssertTrue(libraryText.contains("activeChartPreviewMode"))
        XCTAssertTrue(libraryText.contains("Label(\"Delete Local\", systemImage: \"trash\")"))
        XCTAssertFalse(libraryText.contains("IChartBasicChartPruningPanel"))
        XCTAssertFalse(libraryText.contains("Label(\"Remove Local\""))
    }

    func testEditorExitUsesExplicitNavigationRoute() throws {
        let projectRoot = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
        let appRootText = try String(contentsOf: projectRoot.appendingPathComponent("SmartChart/App/AppRootView.swift"))
        let editorText = try String(contentsOf: projectRoot.appendingPathComponent("SmartChart/Features/Editor/EditorView.swift"))

        XCTAssertTrue(appRootText.contains("EditorView(chart: chart, initialCanvasMode: initialCanvasMode)"))
        XCTAssertTrue(appRootText.contains("projectPath.removeAll()"))
        XCTAssertTrue(editorText.contains("private let onExit"))
        XCTAssertTrue(editorText.contains("exitEditor()"))
        XCTAssertTrue(editorText.contains("editorNavigationChrome"))
        XCTAssertTrue(editorText.contains("editorToolChrome"))
        XCTAssertTrue(editorText.contains(".toolbar(.hidden, for: .navigationBar)"))
        XCTAssertTrue(editorText.contains(".frame(width: 44, height: 44)"))
    }

    func testSupabasePackageAndConfigurationAreWired() throws {
        let projectRoot = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
        let projectText = try String(contentsOf: projectRoot.appendingPathComponent("project.yml"))
        let appText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("SmartChart/App/SmartChartApp.swift")
        )
        let configurationText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("SmartChart/App/Supabase/IChartSupabaseConfiguration.swift")
        )
        let authStoreText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("SmartChart/App/Auth/IChartAuthStore.swift")
        )
        let syncServiceText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("SmartChart/App/Sync/ChartCloudSyncService.swift")
        )
        let syncStateText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("SmartChart/Models/ChartSyncState.swift")
        )
        let syncStoreText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("SmartChart/App/Sync/ChartCloudSyncStore.swift")
        )
        let libraryText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("SmartChart/Features/Library/LibraryView.swift")
        )
        let clientFactoryText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("SmartChart/App/Supabase/IChartSupabaseClientFactory.swift")
        )
        let sessionStoreText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("SmartChart/App/Supabase/IChartSupabaseSessionStore.swift")
        )
        let authStorageText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("SmartChart/App/Supabase/IChartSupabaseAuthLocalStorage.swift")
        )

        XCTAssertTrue(projectText.contains("https://github.com/supabase/supabase-swift.git"))
        XCTAssertTrue(projectText.contains("product: Supabase"))
        XCTAssertTrue(projectText.contains("path: SmartChart/App/Info.plist"))
        XCTAssertTrue(projectText.contains("MARKETING_VERSION: \"1.0\""))
        XCTAssertTrue(projectText.contains("CURRENT_PROJECT_VERSION: \"1\""))
        XCTAssertTrue(projectText.contains("SUPABASE_URL: https://pausvvwoazbvmzyrebwl.supabase.co"))
        XCTAssertTrue(projectText.contains("SUPABASE_PUBLISHABLE_KEY: sb_publishable_"))
        XCTAssertFalse(projectText.contains("SUPABASE_SERVICE_ROLE_KEY"))
        XCTAssertFalse(projectText.contains("SUPABASE_SECRET_KEY"))
        XCTAssertTrue(projectText.contains("SupabaseURL: \"$(SUPABASE_URL)\""))
        XCTAssertTrue(projectText.contains("SupabasePublishableKey: \"$(SUPABASE_PUBLISHABLE_KEY)\""))
        XCTAssertTrue(projectText.contains("SupabaseAnonKey: \"$(SUPABASE_ANON_KEY)\""))
        XCTAssertTrue(projectText.contains("CFBundleURLTypes:"))
        XCTAssertTrue(projectText.contains("ichart"))
        XCTAssertTrue(appText.contains("IChartSupabaseClientFactory.liveClients()"))
        XCTAssertTrue(appText.contains("IChartAuthStore.live(clients:"))
        XCTAssertTrue(appText.contains("ChartCloudSyncStore.live(clients:"))
        XCTAssertTrue(configurationText.contains("SUPABASE_URL"))
        XCTAssertTrue(configurationText.contains("SUPABASE_PUBLISHABLE_KEY"))
        XCTAssertTrue(configurationText.contains("SUPABASE_ANON_KEY"))
        XCTAssertTrue(clientFactoryText.contains("SupabaseClient("))
        XCTAssertTrue(clientFactoryText.contains("IChartSupabaseAuthLocalStorage"))
        XCTAssertTrue(clientFactoryText.contains("IChartSupabaseSessionStore"))
        XCTAssertTrue(clientFactoryText.contains("accessToken:"))
        XCTAssertTrue(clientFactoryText.contains("ichart://auth-callback"))
        XCTAssertTrue(clientFactoryText.contains("isAuthCallbackURL"))
        XCTAssertTrue(sessionStoreText.contains("IChartSupabaseSessionRefresher"))
        XCTAssertTrue(sessionStoreText.contains("refreshIfNeeded()"))
        XCTAssertTrue(sessionStoreText.contains("func accessToken() async throws -> String?"))
        XCTAssertTrue(authStorageText.contains("KeychainLocalStorage"))
        XCTAssertTrue(authStorageText.contains("UserDefaults"))
        XCTAssertTrue(authStorageText.contains("allowsInsecureFallback"))
        XCTAssertTrue(authStorageText.contains("#if DEBUG"))
        XCTAssertTrue(authStorageText.contains("targetEnvironment(simulator)"))
        XCTAssertTrue(authStorageText.contains("IChartSupabasePersistentSessionStore"))
        XCTAssertTrue(authStorageText.contains("iChart.supabase.session.v1"))
        XCTAssertTrue(authStoreText.contains("func signUp("))
        XCTAssertTrue(authStoreText.contains("signupMetadata(firstName:"))
        XCTAssertTrue(authStoreText.contains("let session = try await authClient.auth.signIn("))
        XCTAssertTrue(authStoreText.contains("resendVerificationEmail"))
        XCTAssertTrue(authStoreText.contains("resetPasswordForEmail"))
        XCTAssertTrue(authStoreText.contains("Set new password"))
        XCTAssertTrue(authStoreText.contains("passwordRecovery"))
        XCTAssertTrue(authStoreText.contains("updatePassword(_ password:"))
        XCTAssertTrue(authStoreText.contains("UserAttributes(password: password)"))
        XCTAssertTrue(authStoreText.contains("callbackType(from:"))
        XCTAssertTrue(authStoreText.contains("verifyOTP("))
        XCTAssertTrue(authStoreText.contains("tokenHash:"))
        XCTAssertTrue(authStoreText.contains("token_hash"))
        XCTAssertTrue(authStoreText.contains("tokenHashValue(from:"))
        XCTAssertTrue(authStoreText.contains("\"token\""))
        XCTAssertTrue(authStoreText.contains("pendingVerificationEmailStorage"))
        XCTAssertTrue(authStoreText.contains("IChartSupabaseAuthLocalStorage("))
        XCTAssertTrue(authStoreText.contains("allowsInsecureFallback: false"))
        XCTAssertTrue(authStoreText.contains("iChart.pending-verification-email.v1"))
        XCTAssertTrue(authStoreText.contains("legacyPendingVerificationEmailKey"))
        XCTAssertFalse(authStoreText.contains("UserDefaults.standard.set(email"))
        XCTAssertTrue(authStoreText.contains("applyAuthState"))
        XCTAssertTrue(authStoreText.contains("dataClient"))
        XCTAssertTrue(authStoreText.contains("sessionStore.update"))
        XCTAssertTrue(authStoreText.contains("persistentSessionStore.store"))
        XCTAssertTrue(authStoreText.contains("restoreStoredSession"))
        XCTAssertTrue(authStoreText.contains("temporarilyOffline"))
        XCTAssertTrue(authStoreText.contains("Temporarily offline"))
        XCTAssertTrue(authStoreText.contains("Account is offline. Local charts remain available."))
        XCTAssertTrue(authStoreText.contains("isConnectivityError"))
        XCTAssertTrue(authStoreText.contains("setSession("))
        XCTAssertTrue(authStoreText.contains("redirectTo: IChartSupabaseClientFactory.authCallbackURL"))
        XCTAssertTrue(authStoreText.contains("emailRedirectTo: IChartSupabaseClientFactory.authCallbackURL"))
        XCTAssertTrue(authStoreText.contains("IChartUserProfileUpdate"))
        XCTAssertTrue(authStoreText.contains("IChartAuthError.invalidAuthCallback"))
        XCTAssertTrue(authStoreText.contains("session(from:"))
        XCTAssertFalse(authStoreText.contains("client.auth.currentUser"))
        XCTAssertTrue(syncServiceText.contains("existingSnapshotID(chartID:"))
        XCTAssertTrue(syncServiceText.contains("ignoreDuplicates: true"))
        XCTAssertTrue(syncServiceText.contains(".eq(\"version\", value: String(version))"))
        XCTAssertTrue(syncServiceText.contains("sessionRefresher.refreshIfNeeded()"))
        XCTAssertTrue(syncStoreText.contains("IChartSupabaseSessionRefresher"))
        XCTAssertTrue(syncServiceText.contains("localSnapshotForSync"))
        XCTAssertTrue(syncServiceText.contains("shouldRestoreRemoteForLegacyOwnerlessSnapshot"))
        XCTAssertFalse(syncServiceText.contains("client.auth.currentUser"))
        XCTAssertFalse(syncServiceText.contains("enum ChartSyncState"))
        XCTAssertTrue(syncStateText.contains("enum ChartSyncState"))
        XCTAssertTrue(syncStateText.contains("Cloud backup unavailable"))
        XCTAssertTrue(syncStateText.contains("Sign in to back up"))
        XCTAssertTrue(syncStateText.contains("Cloud backup requires Pro"))
        XCTAssertTrue(syncStateText.contains("Upgrade to Pro to back up and restore from cloud."))
        XCTAssertTrue(syncStateText.contains("Reconnect to back up."))
        XCTAssertFalse(syncStateText.contains("Charts are saved " + "locally"))
        XCTAssertFalse(syncStateText.contains("Saved " + "locally"))
        XCTAssertTrue(syncStateText.contains("manualSyncTitle"))
        XCTAssertTrue(syncStateText.contains("Try Again"))
        XCTAssertTrue(syncStateText.contains("Back Up Now"))
        XCTAssertFalse(syncStateText.contains("Retry Sync"))
        XCTAssertFalse(syncStateText.contains("Sync Now"))
        XCTAssertTrue(syncStateText.contains("manualSyncDisabledReason"))
        XCTAssertTrue(syncStoreText.contains("lastSyncAttemptAt"))
        XCTAssertTrue(syncStoreText.contains("cancelPendingSyncWork()"))
        XCTAssertTrue(syncStoreText.contains("case .temporarilyOffline"))
        XCTAssertTrue(syncStoreText.contains(".notConnectedToInternet"))
        XCTAssertTrue(syncStoreText.contains("Sign in again to resume cloud backup."))
        XCTAssertTrue(syncStoreText.contains("Cloud permissions blocked backup. Sign in again, then retry."))
        XCTAssertTrue(syncStoreText.contains("We could not finish cloud backup. Retry when you are online."))
        XCTAssertTrue(libraryText.contains("IChartCloudSyncSettings"))
        XCTAssertTrue(libraryText.contains("Reconnect"))
        XCTAssertTrue(libraryText.contains("Save Password"))
        XCTAssertFalse(libraryText.contains("Last Backup"))
        XCTAssertFalse(libraryText.contains("Last Checked"))
        XCTAssertTrue(libraryText.contains("syncStore.state.manualSyncTitle"))
        XCTAssertTrue(libraryText.contains("syncStore.state.manualSyncDisabledReason"))
        XCTAssertTrue(libraryText.contains("statusTint"))
        XCTAssertFalse(configurationText.contains("eyJ"))
    }

    func testStoreKitSubscriptionAuthorityIsWired() throws {
        let projectRoot = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
        let projectText = try String(contentsOf: projectRoot.appendingPathComponent("project.yml"))
        let appText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("SmartChart/App/SmartChartApp.swift")
        )
        let catalogText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("SmartChart/Models/IChartStoreKitProductCatalog.swift")
        )
        let storeKitText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("SmartChart/App/StoreKit/IChartStoreKitSubscriptionStore.swift")
        )
        let libraryText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("SmartChart/Features/Library/LibraryView.swift")
        )
        let upgradeText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("SmartChart/Features/Editor/Components/UpgradeSheetView.swift")
        )
        let appEntitlementsText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("SmartChart/Models/AppEntitlements.swift")
        )
        let planPolicyText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("docs/ichart-plan-policy-source-of-truth.md")
        )
        let storeKitRunbookText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("docs/ichart-storekit-subscription-runbook.md")
        )
        let storeKitConfigURL = projectRoot
            .appendingPathComponent("StoreKit/iChartProSubscriptions.storekit")
        let storeKitConfigText = try String(contentsOf: storeKitConfigURL)
        let storeKitConfigData = try Data(contentsOf: storeKitConfigURL)
        let storeKitConfigJSON = try XCTUnwrap(
            JSONSerialization.jsonObject(with: storeKitConfigData) as? [String: Any]
        )

        XCTAssertTrue(projectText.contains("fileGroups:"))
        XCTAssertTrue(projectText.contains("SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG"))
        XCTAssertTrue(projectText.contains("- StoreKit"))
        XCTAssertFalse(projectText.contains("- path: StoreKit\n        buildPhase: resources"))
        XCTAssertTrue(projectText.contains("storeKitConfiguration: StoreKit/iChartProSubscriptions.storekit"))
        XCTAssertTrue(catalogText.contains("com.smartchart.app.pro.monthly"))
        XCTAssertTrue(catalogText.contains("com.smartchart.app.pro.annual"))
        XCTAssertTrue(catalogText.contains("localPreviewProductOptions"))
        XCTAssertFalse(catalogText.contains("localStoreKitConfigurationFileName"))
        XCTAssertTrue(catalogText.contains("IChartStoreKitEntitlementResolver"))
        XCTAssertTrue(storeKitConfigText.contains("\"productID\": \"com.smartchart.app.pro.monthly\""))
        XCTAssertTrue(storeKitConfigText.contains("\"productID\": \"com.smartchart.app.pro.annual\""))
        XCTAssertTrue(storeKitConfigText.contains("\"displayPrice\": \"7.99\""))
        XCTAssertTrue(storeKitConfigText.contains("\"displayPrice\": \"64.99\""))
        XCTAssertTrue(storeKitConfigText.contains("\"recurringSubscriptionPeriod\": \"P1M\""))
        XCTAssertTrue(storeKitConfigText.contains("\"recurringSubscriptionPeriod\": \"P1Y\""))
        XCTAssertEqual(
            (storeKitConfigJSON["version"] as? [String: Any])?["major"] as? Int,
            3
        )
        XCTAssertTrue(storeKitText.contains("Product.products(for: productIDs)"))
        XCTAssertTrue(storeKitText.contains("Transaction.currentEntitlements"))
        XCTAssertTrue(storeKitText.contains("Transaction.updates"))
        XCTAssertTrue(storeKitText.contains("#if DEBUG && targetEnvironment(simulator)"))
        XCTAssertTrue(storeKitText.contains("localStoreKitProductOptions()"))
        XCTAssertTrue(storeKitText.contains("IChartStoreKitProductCatalog.localPreviewProductOptions"))
        XCTAssertFalse(storeKitText.contains("Bundle.main.url("))
        XCTAssertFalse(storeKitText.contains("LocalStoreKitConfiguration"))
        XCTAssertTrue(storeKitText.contains("applyLocalPreview(.activePro(verifiedAt: Date()))"))
        XCTAssertTrue(storeKitText.contains("Pro preview is active on this device."))
        XCTAssertTrue(storeKitText.contains("Pro subscriptions are temporarily unavailable."))
        XCTAssertTrue(storeKitText.contains("Pro subscriptions could not be loaded."))
        XCTAssertFalse(storeKitText.contains("Local Pro preview active for simulator QA."))
        XCTAssertFalse(storeKitText.contains("StoreKit products are not configured."))
        XCTAssertFalse(storeKitText.contains("StoreKit products could not be loaded."))
        XCTAssertFalse(storeKitText.contains("Subscription server verification is unavailable. Using local simulator entitlement."))
        XCTAssertTrue(storeKitText.contains("product.purchase()"))
        XCTAssertTrue(storeKitText.contains("AppStore.sync()"))
        XCTAssertTrue(storeKitText.contains("AppStore.showManageSubscriptions(in: scene)"))
        XCTAssertTrue(storeKitText.contains("Opening subscription management..."))
        XCTAssertTrue(storeKitText.contains("IChartStoreKitEntitlementResolver.entitlement"))
        XCTAssertTrue(storeKitText.contains("FunctionInvokeOptions"))
        XCTAssertTrue(storeKitText.contains("jwsRepresentation"))
        XCTAssertTrue(storeKitText.contains("\"storekit-subscription-claims\""))
        XCTAssertTrue(storeKitText.contains("loadRemoteSubscriptionEntitlement"))
        XCTAssertTrue(appText.contains("@StateObject private var subscriptionStore"))
        XCTAssertTrue(appText.contains("IChartStoreKitSubscriptionStore.live(clients: supabaseClients)"))
        XCTAssertTrue(appText.contains("await subscriptionStore.bootstrap()"))
        XCTAssertTrue(appText.contains("await subscriptionStore.refreshEntitlements()"))
        XCTAssertTrue(appText.contains("applySubscriptionState(subscriptionStore.entitlement)"))
        XCTAssertTrue(appText.contains("store.applySubscriptionState(entitlement)"))
        XCTAssertTrue(appText.contains("pdfLibraryStore.removeForumDownloadsIfInactive(for: entitlement)"))
        XCTAssertTrue(appText.contains(".environmentObject(subscriptionStore)"))
        XCTAssertTrue(libraryText.contains("@EnvironmentObject private var subscriptionStore"))
        XCTAssertTrue(libraryText.contains("Pro Subscription"))
        XCTAssertTrue(libraryText.contains("Restore Purchases"))
        XCTAssertTrue(libraryText.contains("Manage Subscription"))
        XCTAssertTrue(libraryText.contains("subscriptionStore.productOptions"))
        XCTAssertTrue(libraryText.contains("Pro subscriptions are temporarily unavailable. Try again later or restore an existing purchase."))
        XCTAssertTrue(libraryText.contains("Use local preview controls on this device."))
        XCTAssertTrue(libraryText.contains("Sample Forum Charts"))
        XCTAssertFalse(libraryText.contains("StoreKit products are unavailable"))
        XCTAssertFalse(libraryText.contains("Simulator control for StoreKit/Supabase entitlement QA"))
        XCTAssertFalse(libraryText.contains("Forum QA Samples"))
        XCTAssertTrue(libraryText.contains("product.valueBadge"))
        XCTAssertTrue(libraryText.contains("subscriptionStore.applyLocalPreview(subscriptionState)"))
        XCTAssertTrue(libraryText.contains("subscriptionStore.purchase(product)"))
        XCTAssertTrue(libraryText.contains("subscriptionStore.manageSubscriptions()"))
        XCTAssertTrue(upgradeText.contains("@EnvironmentObject private var subscriptionStore"))
        XCTAssertTrue(upgradeText.contains("subscriptionStore.productOptions"))
        XCTAssertTrue(upgradeText.contains("product.valueBadge"))
        XCTAssertTrue(upgradeText.contains("subscriptionStore.purchase(product)"))
        XCTAssertTrue(upgradeText.contains("subscriptionStore.restorePurchases()"))
        XCTAssertTrue(upgradeText.contains("Manage Subscription"))
        XCTAssertTrue(upgradeText.contains("subscriptionStore.manageSubscriptions()"))
        XCTAssertTrue(upgradeText.contains("Pro Preview unlocks Pro locally on this device."))
        XCTAssertTrue(upgradeText.contains("Pro subscriptions are temporarily unavailable. Try again later or restore an existing purchase."))
        XCTAssertTrue(upgradeText.contains("Projects for song variants"))
        XCTAssertTrue(appEntitlementsText.contains("Instrument Transposition"))
        XCTAssertTrue(appEntitlementsText.contains("Repeats And Coda"))
        XCTAssertTrue(appEntitlementsText.contains("Rhythm Editing"))
        XCTAssertFalse(appEntitlementsText.contains("Transposition Views"))
        XCTAssertFalse(appEntitlementsText.contains("Transposition views"))
        XCTAssertFalse(appEntitlementsText.contains("section charts, keys"))
        XCTAssertFalse(upgradeText.contains("Cross-device sync when available"))
        XCTAssertFalse(libraryText.contains("future service-backed features"))
        XCTAssertFalse(libraryText.contains("future multi-device work"))
        XCTAssertFalse(upgradeText.contains("simulator entitlement QA"))
        XCTAssertFalse(upgradeText.contains("monthly and annual product IDs"))
        XCTAssertFalse(upgradeText.contains("until StoreKit is wired"))
        XCTAssertTrue(planPolicyText.contains("StoreKit owns Apple subscription purchase/restore."))
        XCTAssertTrue(planPolicyText.contains("StoreKit/iChartProSubscriptions.storekit"))
        XCTAssertTrue(planPolicyText.contains("Supabase subscription rows are read-only from the app and are updated only by trusted server-side purchase verification"))
        XCTAssertTrue(storeKitRunbookText.contains("com.smartchart.app.pro.monthly"))
        XCTAssertTrue(storeKitRunbookText.contains("com.smartchart.app.pro.annual"))
        XCTAssertTrue(storeKitRunbookText.contains("$7.99/month"))
        XCTAssertTrue(storeKitRunbookText.contains("$64.99/year"))
        XCTAssertTrue(storeKitRunbookText.contains("StoreKit/iChartProSubscriptions.storekit"))
        XCTAssertTrue(storeKitRunbookText.contains("App Store Connect Production Gate"))
        XCTAssertTrue(storeKitRunbookText.contains("subscription group for iChart Pro"))
        XCTAssertTrue(storeKitRunbookText.contains("up to 1 hour to appear in the sandbox environment"))
        XCTAssertTrue(storeKitRunbookText.contains("App Store Server Notifications"))
        XCTAssertTrue(storeKitRunbookText.contains("App Store Server API"))
        XCTAssertTrue(storeKitRunbookText.contains("Settings and the upgrade sheet expose Manage Subscription"))
        XCTAssertTrue(storeKitRunbookText.contains("Have the verified server path write the subscription authority metadata in `subscriptions`; the iOS app remains select-only."))
        XCTAssertTrue(storeKitRunbookText.contains("StoreKit is an entitlement source"))
        XCTAssertTrue(storeKitRunbookText.contains("Keep service-role keys, webhook secrets, App Store Connect API keys, and signing keys out of the iOS app and out of git."))
    }

    func testAppStoreServerNotificationFunctionIsLockedBehindVerificationAndServerWrites() throws {
        let projectRoot = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
        let supabaseConfigText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("supabase/config.toml")
        )
        let functionText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("supabase/functions/app-store-server-notifications/index.mjs")
        )
        let claimFunctionText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("supabase/functions/storekit-subscription-claims/index.mjs")
        )
        let authorityText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("supabase/functions/_shared/app_store_subscription_authority.mjs")
        )
        let authorityStoreText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("supabase/functions/_shared/supabase_subscription_authority_store.mjs")
        )
        let authorityTestText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("supabase/functions/_shared/app_store_subscription_authority.test.mjs")
        )
        let authorityStoreTestText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("supabase/functions/_shared/supabase_subscription_authority_store.test.mjs")
        )
        let signedVerifierText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("supabase/functions/_shared/app_store_signed_data_verifier.mjs")
        )
        let verifierConfigText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("supabase/functions/_shared/app_store_verifier_config.mjs")
        )
        let verifierConfigTestText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("supabase/functions/_shared/app_store_verifier_config.test.mjs")
        )
        let storeKitRunbookText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("docs/ichart-storekit-subscription-runbook.md")
        )
        let productionReadinessText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("docs/supabase-production-readiness-checklist.md")
        )
        let planPolicyText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("docs/ichart-plan-policy-source-of-truth.md")
        )

        XCTAssertTrue(supabaseConfigText.contains("[functions.app-store-server-notifications]"))
        XCTAssertTrue(supabaseConfigText.contains("verify_jwt = false"))
        XCTAssertTrue(supabaseConfigText.contains("entrypoint = \"./functions/app-store-server-notifications/index.mjs\""))
        XCTAssertTrue(supabaseConfigText.contains("[functions.storekit-subscription-claims]"))
        XCTAssertTrue(supabaseConfigText.contains("verify_jwt = true"))
        XCTAssertTrue(supabaseConfigText.contains("entrypoint = \"./functions/storekit-subscription-claims/index.mjs\""))
        XCTAssertFalse(supabaseConfigText.contains("app-store-server-notifications/index.ts"))
        XCTAssertFalse(supabaseConfigText.contains("@supabase/server"))
        XCTAssertTrue(functionText.contains("handleAppStoreServerNotificationRequest"))
        XCTAssertTrue(claimFunctionText.contains("handleStoreKitSubscriptionClaimRequest"))
        XCTAssertTrue(functionText.contains("createAppStoreSignedDataVerifiers"))
        XCTAssertTrue(claimFunctionText.contains("createAppStoreSignedDataVerifiers"))
        XCTAssertTrue(functionText.contains("createSupabaseSubscriptionAuthorityDependencies"))
        XCTAssertTrue(claimFunctionText.contains("createSupabaseSubscriptionAuthorityDependencies"))
        XCTAssertFalse(functionText.contains("Hello from Functions"))
        XCTAssertFalse(functionText.contains("withSupabase"))
        XCTAssertFalse(claimFunctionText.contains("withSupabase"))
        XCTAssertTrue(authorityText.contains("com.smartchart.app.pro.monthly"))
        XCTAssertTrue(authorityText.contains("com.smartchart.app.pro.annual"))
        XCTAssertTrue(authorityText.contains("App Store signedPayload verification is not configured."))
        XCTAssertTrue(authorityText.contains("writeSubscriptionAuthority"))
        XCTAssertTrue(authorityText.contains("Missing App Store signedPayload."))
        XCTAssertTrue(authorityText.contains("Nested App Store signed payload verification is not configured."))
        XCTAssertTrue(authorityText.contains("Verified App Store payload is missing subscription identity fields."))
        XCTAssertTrue(authorityText.contains("StoreKit signed transaction verification is not configured."))
        XCTAssertTrue(authorityText.contains("writeSubscriptionAuthorityClaim"))
        XCTAssertTrue(authorityText.contains("Verified StoreKit transaction is not an iChart Pro subscription."))
        XCTAssertTrue(authorityText.contains("Authenticated user resolver is not configured."))
        XCTAssertTrue(authorityText.contains("mapping_status"))
        XCTAssertTrue(authorityStoreText.contains("SUPABASE_SECRET_KEYS"))
        XCTAssertTrue(authorityStoreText.contains("SUPABASE_SERVICE_ROLE_KEY"))
        XCTAssertTrue(authorityStoreText.contains("authenticatedUserIDFromBearer"))
        XCTAssertTrue(authorityStoreText.contains("on_conflict"))
        XCTAssertTrue(authorityStoreText.contains("storekit_original_transaction_id"))
        XCTAssertTrue(authorityStoreText.contains("unmapped_original_transaction"))
        XCTAssertTrue(authorityTestText.contains("webhook refuses to process signedPayload without verifier"))
        XCTAssertTrue(authorityTestText.contains("webhook refuses nested signed payloads until nested verifiers are configured"))
        XCTAssertTrue(authorityTestText.contains("webhook refuses verified payloads without subscription identity fields"))
        XCTAssertTrue(authorityTestText.contains("transaction claim refuses to process without verifier"))
        XCTAssertTrue(authorityTestText.contains("transaction claim writes only after user and transaction are verified"))
        XCTAssertTrue(authorityTestText.contains("webhook accepts verified unmapped transactions without inventing ownership"))
        XCTAssertTrue(authorityTestText.contains("unknown products never unlock pro"))
        XCTAssertTrue(authorityStoreTestText.contains("claim writer upserts subscription authority by owner"))
        XCTAssertTrue(authorityStoreTestText.contains("notification writer patches only previously claimed original transactions"))
        XCTAssertTrue(authorityStoreTestText.contains("authenticated user resolver validates bearer token"))
        XCTAssertTrue(signedVerifierText.contains("@apple/app-store-server-library@3.1.0"))
        XCTAssertTrue(signedVerifierText.contains("SignedDataVerifier"))
        XCTAssertTrue(signedVerifierText.contains("verifyAndDecodeNotification"))
        XCTAssertTrue(signedVerifierText.contains("verifyAndDecodeTransaction"))
        XCTAssertTrue(signedVerifierText.contains("verifyAndDecodeRenewalInfo"))
        XCTAssertTrue(verifierConfigText.contains("APP_STORE_BUNDLE_ID"))
        XCTAssertTrue(verifierConfigText.contains("APP_STORE_ENVIRONMENT"))
        XCTAssertTrue(verifierConfigText.contains("APP_STORE_ROOT_CERTIFICATES_PEM"))
        XCTAssertTrue(verifierConfigText.contains("APP_STORE_APP_APPLE_ID"))
        XCTAssertTrue(verifierConfigTestText.contains("requires App Apple ID for production verification"))
        XCTAssertTrue(verifierConfigTestText.contains("allows sandbox configuration without an App Apple ID"))
        XCTAssertTrue(storeKitRunbookText.contains("supabase/functions/app-store-server-notifications/index.mjs"))
        XCTAssertTrue(storeKitRunbookText.contains("supabase/functions/storekit-subscription-claims/index.mjs"))
        XCTAssertTrue(storeKitRunbookText.contains("supabase/functions/_shared/app_store_signed_data_verifier.mjs"))
        XCTAssertTrue(storeKitRunbookText.contains("supabase/functions/_shared/supabase_subscription_authority_store.mjs"))
        XCTAssertTrue(storeKitRunbookText.contains("APP_STORE_ROOT_CERTIFICATES_PEM"))
        XCTAssertTrue(storeKitRunbookText.contains("APP_STORE_APP_APPLE_ID"))
        XCTAssertTrue(storeKitRunbookText.contains("supabase/functions/_shared/app_store_subscription_authority.test.mjs"))
        XCTAssertTrue(storeKitRunbookText.contains("supabase/functions/_shared/supabase_subscription_authority_store.test.mjs"))
        XCTAssertTrue(storeKitRunbookText.contains("supabase/functions/_shared/app_store_verifier_config.test.mjs"))
        XCTAssertTrue(storeKitRunbookText.contains("Apple's official `@apple/app-store-server-library` `SignedDataVerifier`"))
        XCTAssertTrue(storeKitRunbookText.contains("invalid Apple signatures are rejected before mapping or writing"))
        XCTAssertTrue(storeKitRunbookText.contains("The authenticated claim endpoint creates the trusted account-to-original-transaction mapping"))
        XCTAssertTrue(storeKitRunbookText.contains("unmapped notifications are accepted without assigning ownership"))
        XCTAssertTrue(productionReadinessText.contains("App Store Server Notifications are received by `app-store-server-notifications`."))
        XCTAssertTrue(productionReadinessText.contains("StoreKit transaction claims are received by `storekit-subscription-claims`."))
        XCTAssertTrue(productionReadinessText.contains("The server-only subscription writer reads Edge Function secrets and never runs in the iOS app."))
        XCTAssertTrue(productionReadinessText.contains("Nested App Store transaction/renewal payloads must also be verified"))
        XCTAssertTrue(productionReadinessText.contains("Verified transaction claims must resolve the signed-in Supabase user before writing owner mapping."))
        XCTAssertTrue(productionReadinessText.contains("Apple JWS verification is wired through Apple's `SignedDataVerifier`"))
        XCTAssertTrue(productionReadinessText.contains("APP_STORE_ROOT_CERTIFICATES_PEM"))
        XCTAssertTrue(planPolicyText.contains("uses Apple's signed-data verifier and an Edge-only Supabase writer when secrets are configured"))
        XCTAssertTrue(planPolicyText.contains("StoreKit transaction claiming is the authenticated path that maps an Apple original transaction to an iChart account"))
    }

    func testSupabaseMigrationCreatesProtectedAccountAndChartTables() throws {
        let projectRoot = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
        let migrationText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("supabase/migrations/20260609133000_initial_auth_profiles_and_charts.sql")
        )
        let appStoreSubscriptionMigrationText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("supabase/migrations/20260612232613_harden_app_store_subscription_authority.sql")
        )
        let configText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("supabase/config.toml")
        )

        XCTAssertTrue(migrationText.contains("create table public.profiles"))
        XCTAssertTrue(migrationText.contains("create table public.chart_documents"))
        XCTAssertTrue(migrationText.contains("create table public.chart_snapshots"))
        XCTAssertTrue(migrationText.contains("create table public.subscriptions"))
        XCTAssertTrue(migrationText.contains("create table public.devices"))
        XCTAssertTrue(migrationText.contains("deleted_at timestamptz"))
        XCTAssertTrue(migrationText.contains("remote_revision bigint"))
        XCTAssertTrue(migrationText.contains("client_updated_at timestamptz"))
        XCTAssertTrue(migrationText.contains("enable row level security"))
        XCTAssertTrue(migrationText.contains("auth.uid() = owner_id"))
        XCTAssertTrue(migrationText.contains("auth.uid() = id"))
        XCTAssertTrue(migrationText.contains("chart_snapshots.chart_id = chart_documents.id"))
        XCTAssertTrue(migrationText.contains("handle_new_auth_user"))
        XCTAssertTrue(migrationText.contains("stripe_customer_id"))
        XCTAssertTrue(migrationText.contains("revoke all on table public.subscriptions from anon, authenticated"))
        XCTAssertTrue(migrationText.contains("grant select on table public.subscriptions to authenticated"))
        XCTAssertTrue(migrationText.contains("grant insert (id, email, phone, mailing_address, payment_summary)"))
        XCTAssertTrue(appStoreSubscriptionMigrationText.contains("provider text not null default 'none'"))
        XCTAssertTrue(appStoreSubscriptionMigrationText.contains("storekit_product_id text"))
        XCTAssertTrue(appStoreSubscriptionMigrationText.contains("storekit_original_transaction_id text"))
        XCTAssertTrue(appStoreSubscriptionMigrationText.contains("storekit_environment text"))
        XCTAssertTrue(appStoreSubscriptionMigrationText.contains("app_store_status text"))
        XCTAssertTrue(appStoreSubscriptionMigrationText.contains("app_store_notification_type text"))
        XCTAssertTrue(appStoreSubscriptionMigrationText.contains("app_store_last_transaction_id text"))
        XCTAssertTrue(appStoreSubscriptionMigrationText.contains("entitlement_expires_at timestamptz"))
        XCTAssertTrue(appStoreSubscriptionMigrationText.contains("grace_period_expires_at timestamptz"))
        XCTAssertTrue(appStoreSubscriptionMigrationText.contains("last_verified_at timestamptz"))
        XCTAssertTrue(appStoreSubscriptionMigrationText.contains("subscriptions_provider_check"))
        XCTAssertTrue(appStoreSubscriptionMigrationText.contains("subscriptions_storekit_original_transaction_id_idx"))
        XCTAssertFalse(migrationText.contains("chart_snapshots_update_own"))
        XCTAssertFalse(migrationText.contains("card_number"))
        XCTAssertTrue(configText.contains("max_frequency = \"1m\""))
        XCTAssertTrue(configText.contains("otp_length = 6"))
    }

    func testSupabaseRunbookAndRlsSmokeTestsArePresent() throws {
        let projectRoot = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
        let gitignoreText = try String(contentsOf: projectRoot.appendingPathComponent(".gitignore"))
        let envExampleText = try String(contentsOf: projectRoot.appendingPathComponent(".env.example"))
        let runbookText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("docs/supabase-integration-runbook.md")
        )
        let productionReadinessText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("docs/supabase-production-readiness-checklist.md")
        )
        let rlsTestText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("supabase/tests/rls_smoke.sql")
        )
        let supabaseConfigText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("supabase/config.toml")
        )
        let integrationTestText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("SmartChartTests/SupabaseIntegrationTests.swift")
        )
        let qaScriptText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("scripts/run_supabase_local_qa.sh")
        )
        let productionReadinessScriptText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("scripts/run_supabase_production_readiness.sh")
        )

        XCTAssertTrue(gitignoreText.contains("!.env.example"))
        XCTAssertTrue(envExampleText.contains("SUPABASE_URL"))
        XCTAssertTrue(envExampleText.contains("SUPABASE_PUBLISHABLE_KEY"))
        XCTAssertFalse(envExampleText.contains("eyJ"))
        XCTAssertTrue(runbookText.contains("supabase db reset"))
        XCTAssertTrue(runbookText.contains("supabase db push"))
        XCTAssertTrue(runbookText.contains("ichart://auth-callback"))
        XCTAssertTrue(runbookText.contains("blank browser page"))
        XCTAssertTrue(runbookText.contains("custom SMTP"))
        XCTAssertTrue(runbookText.contains("supabase status -o env"))
        XCTAssertTrue(runbookText.contains("remote project settings cannot accidentally redirect local RLS/integration tests"))
        XCTAssertTrue(runbookText.contains("scripts/run_supabase_production_readiness.sh"))
        XCTAssertTrue(runbookText.contains("docs/supabase-production-readiness-checklist.md"))
        XCTAssertTrue(productionReadinessText.contains("Auth email/password provider is enabled"))
        XCTAssertTrue(productionReadinessText.contains("ichart://auth-callback"))
        XCTAssertTrue(productionReadinessText.contains("Email templates keep a confirmation link flow"))
        XCTAssertTrue(productionReadinessText.contains("service-role keys"))
        XCTAssertTrue(productionReadinessText.contains("Back Up Now"))
        XCTAssertTrue(productionReadinessText.contains("Try Again"))
        XCTAssertTrue(productionReadinessText.contains("Restore/Reinstall Gate"))
        XCTAssertTrue(productionReadinessText.contains("Data And RLS Gate"))
        XCTAssertTrue(productionReadinessText.contains("Subscription rows include server-owned provider, StoreKit product, original transaction, App Store status, expiration, grace, revocation, and last-verification metadata."))
        XCTAssertTrue(supabaseConfigText.contains("project_id = \"smart-chart\""))
        XCTAssertTrue(supabaseConfigText.contains("additional_redirect_urls = [\"ichart://auth-callback\"]"))
        XCTAssertTrue(supabaseConfigText.contains("enable_confirmations = true"))
        XCTAssertTrue(supabaseConfigText.contains("secure_password_change = true"))
        XCTAssertTrue(supabaseConfigText.contains("max_frequency = \"1m\""))
        XCTAssertTrue(supabaseConfigText.contains("otp_length = 6"))
        XCTAssertTrue(rlsTestText.contains("owner can insert own chart document"))
        XCTAssertTrue(rlsTestText.contains("client cannot update subscription rows"))
        XCTAssertTrue(rlsTestText.contains("owner can read server-owned subscription authority fields"))
        XCTAssertTrue(rlsTestText.contains("client cannot update app store subscription authority fields"))
        XCTAssertTrue(rlsTestText.contains("client cannot update stripe customer id on profile"))
        XCTAssertTrue(rlsTestText.contains("latest snapshot pointer cannot reference a missing snapshot"))
        XCTAssertTrue(integrationTestText.contains("SMART_CHART_SUPABASE_INTEGRATION"))
        XCTAssertTrue(integrationTestText.contains("SUPABASE_PUBLISHABLE_KEY"))
        XCTAssertTrue(integrationTestText.contains("confirmLocalSignupEmail"))
        XCTAssertTrue(integrationTestText.contains("over_email_send_rate_limit"))
        XCTAssertTrue(integrationTestText.contains("latest_snapshot_id"))
        XCTAssertTrue(integrationTestText.contains("SUPABASE_SERVICE_ROLE_KEY"))
        XCTAssertTrue(integrationTestText.contains("adminCreateConfirmedUser"))
        XCTAssertTrue(integrationTestText.contains("testLiveSupabaseForumPublishVoteCommentReportAndStorageFlow"))
        XCTAssertTrue(qaScriptText.contains("SUPABASE_CMD"))
        XCTAssertTrue(qaScriptText.contains("npx --yes supabase"))
        XCTAssertTrue(qaScriptText.contains("supabase_cli db reset"))
        XCTAssertTrue(qaScriptText.contains("supabase_cli status -o env"))
        XCTAssertTrue(qaScriptText.contains("API_URL"))
        XCTAssertTrue(qaScriptText.contains("PUBLISHABLE_KEY"))
        XCTAssertTrue(qaScriptText.contains("SERVICE_ROLE_KEY"))
        XCTAssertTrue(qaScriptText.contains("supabase_cli test db"))
        XCTAssertTrue(qaScriptText.contains("--filter SupabaseIntegrationTests"))
        XCTAssertTrue(productionReadinessScriptText.contains("git diff --check"))
        XCTAssertTrue(productionReadinessScriptText.contains("scan_for_secrets"))
        XCTAssertTrue(productionReadinessScriptText.contains("supabase/functions/_shared/app_store_subscription_authority.test.mjs"))
        XCTAssertTrue(productionReadinessScriptText.contains("supabase/functions/_shared/app_store_verifier_config.test.mjs"))
        XCTAssertTrue(productionReadinessScriptText.contains("SMART_CHART_RUN_LOCAL_SUPABASE_QA"))
        XCTAssertTrue(productionReadinessScriptText.contains("scripts/run_supabase_local_qa.sh"))
        XCTAssertTrue(productionReadinessScriptText.contains("ProjectConfigurationTests|ChartCloudMergeTests|ChartLibraryStoreTests|SupabaseIntegrationTests"))
        XCTAssertTrue(productionReadinessScriptText.contains("SUPABASE_SERVICE_ROLE_KEY"))
        XCTAssertTrue(productionReadinessScriptText.contains("Manual simulator/cloud gate still required"))
    }

    func testForumCommunityLibraryInfrastructureIsProOnlyAndSnapshotBased() throws {
        let projectRoot = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
        let migrationDirectory = projectRoot.appendingPathComponent("supabase/migrations")
        let forumMigrationText = try FileManager.default
            .contentsOfDirectory(at: migrationDirectory, includingPropertiesForKeys: nil)
            .filter { $0.pathExtension == "sql" && $0.lastPathComponent.contains("forum") }
            .sorted { $0.lastPathComponent < $1.lastPathComponent }
            .map { try String(contentsOf: $0) }
            .joined(separator: "\n")
        let rlsTestText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("supabase/tests/rls_smoke.sql")
        )
        let forumStoreText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("SmartChart/App/Forum/IChartForumStore.swift")
        )
        let libraryText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("SmartChart/Features/Library/LibraryView.swift")
        )
        let editorText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("SmartChart/Features/Editor/EditorView.swift")
        )
        let exporterText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("SmartChart/Services/ChartExporting.swift")
        )
        let pdfLibraryStoreText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("SmartChart/Services/PDFLibraryStore.swift")
        )
        let appText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("SmartChart/App/SmartChartApp.swift")
        )
        let subscriptionText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("SmartChart/Models/IChartSubscriptionEntitlement.swift")
        )
        let pdfPreviewText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("SmartChart/Features/Editor/Components/PDFExportPreviewView.swift")
        )
        let forumCommunityText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("SmartChart/Models/ForumCommunity.swift")
        )
        let planPolicyText = try String(
            contentsOf: projectRoot
                .appendingPathComponent("docs/ichart-plan-policy-source-of-truth.md")
        )

        XCTAssertTrue(forumMigrationText.contains("create table public.forum_songs"))
        XCTAssertTrue(forumMigrationText.contains("create table public.forum_chart_posts"))
        XCTAssertTrue(forumMigrationText.contains("create table public.forum_comments"))
        XCTAssertTrue(forumMigrationText.contains("create table public.forum_votes"))
        XCTAssertTrue(forumMigrationText.contains("create table public.forum_reports"))
        XCTAssertTrue(forumMigrationText.contains("create table public.forum_author_badges"))
        XCTAssertTrue(forumMigrationText.contains("public.current_user_has_active_pro()"))
        XCTAssertTrue(forumMigrationText.contains("storage.buckets"))
        XCTAssertTrue(forumMigrationText.contains("'forum_chart_pdfs'"))
        XCTAssertTrue(forumMigrationText.contains("forum_chart_pdfs_insert_active_pro_owner_folder"))
        XCTAssertTrue(forumMigrationText.contains("forum_chart_pdfs_select_active_pro_visible_post"))
        XCTAssertTrue(forumMigrationText.contains("forum_chart_pdfs_delete_unattached_owner_upload"))
        XCTAssertTrue(forumMigrationText.contains("drop policy if exists \"forum_votes_update_active_pro_own\""))
        XCTAssertTrue(forumMigrationText.contains("drop policy if exists \"forum_votes_delete_active_pro_own\""))
        XCTAssertTrue(forumMigrationText.contains("revoke all on schema private from public"))
        XCTAssertTrue(forumMigrationText.contains("private.refresh_forum_chart_post_quality"))
        XCTAssertTrue(forumMigrationText.contains("status in ('pending', 'published', 'flagged', 'hidden', 'removed')"))
        XCTAssertTrue(forumMigrationText.contains("status = 'pending'"))
        XCTAssertTrue(forumMigrationText.contains("grant insert (status)"))
        XCTAssertFalse(forumMigrationText.contains("chart_json"))
        XCTAssertTrue(rlsTestText.contains("inactive Basic user cannot insert forum songs"))
        XCTAssertTrue(rlsTestText.contains("active Pro can submit forum chart post metadata for review"))
        XCTAssertTrue(rlsTestText.contains("new forum chart posts start pending review"))
        XCTAssertTrue(rlsTestText.contains("another active Pro cannot read pending forum chart posts"))
        XCTAssertTrue(rlsTestText.contains("client cannot update forum moderation status"))
        XCTAssertTrue(rlsTestText.contains("client cannot self-award forum badges"))
        XCTAssertTrue(forumStoreText.contains("static func live(clients:"))
        XCTAssertTrue(forumStoreText.contains("IChartSupabaseSessionRefresher"))
        XCTAssertTrue(forumStoreText.contains("Forum chart submitted for review."))
        XCTAssertTrue(forumStoreText.contains("Sample forum charts loaded."))
        XCTAssertTrue(forumStoreText.contains("Forum Sample.pdf"))
        XCTAssertTrue(forumStoreText.contains("iChart Samples"))
        XCTAssertTrue(forumStoreText.contains("Community review example with reports already attached."))
        XCTAssertTrue(forumStoreText.contains("iChart Forum Sample"))
        XCTAssertFalse(forumStoreText.contains("Forum QA samples loaded."))
        XCTAssertFalse(forumStoreText.contains("QA Forum.pdf"))
        XCTAssertFalse(forumStoreText.contains("iChart QA"))
        XCTAssertFalse(forumStoreText.contains("QA example"))
        XCTAssertFalse(forumStoreText.contains("iChart Forum QA Preview"))
        XCTAssertTrue(forumStoreText.contains("ForumPostModerationStatus.pending.rawValue"))
        XCTAssertTrue(forumStoreText.contains(".requiresPro"))
        XCTAssertTrue(forumStoreText.contains("client.storage"))
        XCTAssertTrue(forumStoreText.contains(".upload("))
        XCTAssertTrue(forumStoreText.contains(".remove(paths:"))
        XCTAssertTrue(forumStoreText.contains(".download(path:"))
        XCTAssertTrue(forumStoreText.contains("ChartPDFExportContext("))
        XCTAssertTrue(forumStoreText.contains("PDFChartExporter"))
        XCTAssertFalse(forumStoreText.contains("chart_json"))
        XCTAssertTrue(libraryText.contains("IChartForumHomeView"))
        XCTAssertTrue(libraryText.contains("Share To Forum"))
        XCTAssertTrue(libraryText.contains("Posted By"))
        XCTAssertTrue(libraryText.contains("Account name required"))
        XCTAssertTrue(libraryText.contains("Submit To Forum"))
        XCTAssertTrue(libraryText.contains("pending an authenticity review"))
        XCTAssertTrue(libraryText.contains("Tags (Optional)"))
        XCTAssertTrue(libraryText.contains("Notes (Optional)"))
        XCTAssertTrue(libraryText.contains("PDF Library"))
        XCTAssertTrue(pdfLibraryStoreText.contains("Forum Downloads"))
        XCTAssertTrue(libraryText.contains("Community Library Unavailable"))
        XCTAssertTrue(libraryText.contains("Community Bandstand"))
        XCTAssertTrue(libraryText.contains("iChart Pro"))
        XCTAssertTrue(libraryText.contains("Find working chord and rhythm PDFs, shout out clean charts, and help other musicians get through rehearsal faster."))
        XCTAssertTrue(libraryText.contains("Contributions"))
        XCTAssertTrue(libraryText.contains("Downloads"))
        XCTAssertTrue(libraryText.contains("Upvotes"))
        XCTAssertTrue(libraryText.contains("Badges"))
        XCTAssertTrue(libraryText.contains("Not For Me"))
        XCTAssertFalse(libraryText.contains("Downvote"))
        XCTAssertTrue(forumCommunityText.contains("upvote"))
        XCTAssertFalse(forumCommunityText.contains("up /"))
        XCTAssertTrue(libraryText.contains("Top Rated"))
        XCTAssertTrue(libraryText.contains("Top Charts"))
        XCTAssertTrue(libraryText.contains("Top 10"))
        XCTAssertTrue(libraryText.contains("Lead Chart"))
        XCTAssertTrue(libraryText.contains("Today"))
        XCTAssertTrue(libraryText.contains("This Week"))
        XCTAssertTrue(libraryText.contains("This Month"))
        XCTAssertTrue(libraryText.contains("All Time"))
        XCTAssertTrue(libraryText.contains("No charts yet"))
        XCTAssertTrue(libraryText.contains("Submit From Your Library"))
        XCTAssertTrue(libraryText.contains("No Chart On This Tune Yet"))
        XCTAssertTrue(libraryText.contains("Search songs, artists, arrangers, or tags"))
        XCTAssertTrue(libraryText.contains("Search Results"))
        XCTAssertTrue(libraryText.contains("Show \\("))
        XCTAssertTrue(libraryText.contains("more"))
        XCTAssertFalse(libraryText.contains("Bandstand Bulletin"))
        XCTAssertFalse(libraryText.contains("Search Community Charts"))
        XCTAssertFalse(libraryText.contains("Arrangement credit:"))
        XCTAssertTrue(libraryText.contains("pdfLibraryStore.save(downloadedPDF, source: .forumDownload)"))
        XCTAssertFalse(libraryText.contains("Forum Services Offline"))
        XCTAssertFalse(libraryText.contains("Publish Chart"))
        XCTAssertFalse(libraryText.contains("Local iChart charts only"))
        XCTAssertFalse(libraryText.contains("PDF snapshots only"))
        XCTAssertFalse(libraryText.contains("No editable chart files"))
        XCTAssertFalse(libraryText.contains("Account names shown"))
        XCTAssertFalse(libraryText.contains("The Bandstand Is Open"))
        XCTAssertFalse(libraryText.contains("Shout Outs"))
        XCTAssertFalse(libraryText.contains("Pro Community"))
        XCTAssertFalse(libraryText.contains("Forum Credit"))
        XCTAssertFalse(libraryText.contains("email: authStore.state.signedInSession?.email"))
        XCTAssertFalse(libraryText.contains("LabeledContent(\"App chart\""))
        XCTAssertFalse(libraryText.contains("LabeledContent(\"Upload source\""))
        XCTAssertFalse(libraryText.contains("LabeledContent(\"Forum format\""))
        XCTAssertFalse(libraryText.contains("forumTextField(\"Chart Title\""))
        XCTAssertFalse(libraryText.contains("forumTextField(\"Creator Display\""))
        XCTAssertFalse(libraryText.contains("fileImporter"))
        XCTAssertFalse(libraryText.contains("UIDocumentPicker"))
        XCTAssertFalse(libraryText.contains("PhotosPicker"))
        XCTAssertTrue(libraryText.contains("Forums require Pro"))
        XCTAssertTrue(libraryText.contains("This chart is no longer available in Forums."))
        XCTAssertTrue(libraryText.contains("Discussion is closed for this chart."))
        XCTAssertTrue(exporterText.contains("ForumPDFCredit"))
        XCTAssertTrue(exporterText.contains("Shared from iChart Forums"))
        XCTAssertTrue(pdfLibraryStoreText.contains("IChartPDFLibraryStore"))
        XCTAssertTrue(pdfLibraryStoreText.contains(".applicationSupportDirectory"))
        XCTAssertTrue(pdfLibraryStoreText.contains("pdf-library.json"))
        XCTAssertTrue(pdfLibraryStoreText.contains("case chartExport"))
        XCTAssertTrue(pdfLibraryStoreText.contains("case forumDownload"))
        XCTAssertTrue(pdfLibraryStoreText.contains("visibleItems(for subscription: IChartSubscriptionEntitlement)"))
        XCTAssertTrue(pdfLibraryStoreText.contains("removeForumDownloadsIfInactive(for subscription: IChartSubscriptionEntitlement)"))
        XCTAssertTrue(appText.contains("pdfLibraryStore.removeForumDownloadsIfInactive(for: entitlement)"))
        XCTAssertTrue(libraryText.contains("pdfLibraryStore.visibleItems(for: store.subscriptionState)"))
        XCTAssertTrue(libraryText.contains("applyForumDownloadAccess(subscriptionPreview)"))
        XCTAssertTrue(subscriptionText.contains("var allowsForumDownloadAccess"))
        XCTAssertTrue(subscriptionText.contains("case .proActive, .proGrace"))
        XCTAssertTrue(subscriptionText.contains("var shouldRemoveForumDownloads"))
        XCTAssertTrue(subscriptionText.contains("case .basic, .proExpired, .legacyLocalPro"))
        XCTAssertFalse(pdfPreviewText.contains("PDF Library"))
        XCTAssertFalse(pdfPreviewText.contains("Saved to " + "PDF Library"))
        XCTAssertFalse(pdfPreviewText.contains("exportedAt.formatted"))
        XCTAssertFalse(libraryText.contains("title: \"Storage\""))
        XCTAssertFalse(libraryText.contains("store.persistenceStatus.displayText"))
        XCTAssertFalse(libraryText.contains("store.persistenceStatus.systemImageName"))
        XCTAssertFalse(libraryText.contains("ChartLibraryPersistenceStatusBadge"))
        XCTAssertFalse(libraryText.contains("item.createdAt.formatted"))
        XCTAssertFalse(editorText.contains("ChartLibraryPersistenceStatusBadge"))
        XCTAssertTrue(planPolicyText.contains("community chart library"))
        XCTAssertTrue(planPolicyText.contains("Forum downloads save into the local in-app PDF Library"))
        XCTAssertTrue(planPolicyText.contains("editable chart JSON, source ink, and local authoring state are not shared in V1"))
        XCTAssertTrue(planPolicyText.contains("users cannot self-award badges"))
    }
}
