create or replace view private.telemetry_recent_ink_diagnostics as
select
    received_at,
    owner_id,
    installation_id,
    app_version,
    build_number,
    os_version,
    device_model,
    event_name,
    properties ->> 'scope' as scope,
    properties ->> 'stroke_count' as stroke_count,
    properties ->> 'point_count' as point_count,
    properties ->> 'light_stroke_count' as light_stroke_count,
    properties ->> 'min_opacity' as min_opacity,
    properties ->> 'median_opacity' as median_opacity,
    properties ->> 'max_opacity' as max_opacity,
    properties ->> 'min_width' as min_width,
    properties ->> 'median_width' as median_width,
    properties ->> 'max_width' as max_width,
    properties ->> 'has_mask' as has_mask,
    properties ->> 'normalization_needed' as normalization_needed,
    properties ->> 'normalized_before_save' as normalized_before_save,
    properties ->> 'stroke_color_min_luminance' as stroke_color_min_luminance,
    properties ->> 'stroke_color_median_luminance' as stroke_color_median_luminance,
    properties ->> 'stroke_color_max_luminance' as stroke_color_max_luminance,
    properties ->> 'tool_ink_type' as tool_ink_type,
    properties ->> 'tool_color_luminance' as tool_color_luminance,
    properties ->> 'canvas_user_interface_style' as canvas_user_interface_style,
    properties ->> 'canvas_background_alpha' as canvas_background_alpha,
    properties ->> 'canvas_is_opaque' as canvas_is_opaque,
    properties ->> 'rendered_ink_median_luminance' as rendered_ink_median_luminance,
    properties ->> 'rendered_ink_light_pixel_ratio' as rendered_ink_light_pixel_ratio,
    properties ->> 'rendered_ink_sample_count' as rendered_ink_sample_count
from public.telemetry_events
where event_name in ('ink.persisted', 'ink.normalization_applied', 'ink.visibility_probe');
